/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    Auth: {
        region: 'eu-north-1',
        aws_user_pools_id: 'eu-north-1_tOB9Nzu7k',
        mandatorySignIn: true,
    },
    "aws_project_region": "eu-north-1",
    "aws_appsync_graphqlEndpoint": "https://knhixo5nczg7nfbmk5oumwl2yy.appsync-api.eu-north-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-north-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vzlbsrn7ina2fbno4qnzjzabee",
    "aws_cognito_identity_pool_id": "eu-north-1:33f3efe5-e3c0-477d-9125-a9d979bd6727",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_tOB9Nzu7k",
    "aws_user_pools_web_client_id": "2gn9r7k1sihtmu2tvcr94b54gg",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
